#!/bin/bash
basedir="$(dirname "$(readlink -f "${0}")")"
#somechecks
command -v inkscape >/dev/null 2>&1 || { echo >&2 "I require Inkscape but it's not installed.  Aborting."; exit 1; }
command -v convert >/dev/null 2>&1 || { echo >&2 "I require ImageMagick but it's not installed.  Aborting."; exit 1; }
command -v gtk-update-icon-cache >/dev/null 2>&1 || { echo >&2 "I require libgtk2-bin but it's not installed.  Aborting."; exit 1; }
cd $basedir
sizes="16
22
24
32
48"

mkdir -p ivy/16
mkdir -p ivy/22
mkdir -p ivy/24
mkdir -p ivy/32
mkdir -p ivy/48
cp -R ivy-dev/16/pool ivy/16
cp -R ivy-dev/22/pool ivy/22
cp -R ivy-dev/32/pool ivy/32
cp -R ivy-dev/48/pool ivy/48
cp ivy-dev/COPYING ivy
cp ivy-dev/COPYING.pdf ivy
cp ivy-dev/index.theme.48 ivy/index.theme
cp ivy-dev/freedesktop-status.html ivy/freedesktop-status.html
#coverting the svg to pngs
cd ivy/16/pool
for name16 in `find  -wholename "*.svg"`; do
inkscape -z $type --export-area-page --export-width=16 --export-height=16 --export-png="`echo "$name16" | sed "s/\.\w*$/.png/"`" "$name16"
done
rm *.svg
cd ../../22/pool
for name24 in `find  -wholename "*.svg"`; do
inkscape -z $type --export-area-page --export-width=22 --export-height=22 --export-png="`echo "$name24" | sed "s/\.\w*$/.png/"`" "$name24"
done
rm *.svg
cd ../../32/pool
for name32 in `find  -wholename "*.svg"`; do
inkscape -z $type --export-area-page --export-width=32 --export-height=32 --export-png="`echo "$name32" | sed "s/\.\w*$/.png/"`" "$name32"
done
rm *.svg
cd ../../48/pool
for name48 in `find  -wholename "*.svg"`; do
inkscape -z $type --export-area-page --export-width=48 --export-height=48 --export-png="`echo "$name48" | sed "s/\.\w*$/.png/"`" "$name48"
done
rm *.svg
cd ../../../
#fix 24px icons
cp -R ivy/22/pool ivy/24
cd ivy/24
for name24 in `find  -wholename "*.png"`; do
#convert -bordercolor Transparent -border 1x1 "$name24" "$name24"
convert -gravity center -extent 24x24 -background Transparent "$name24" -set colorspace RGB "$name24"
done
#copying symlinks
cd $basedir/ivy-dev/48/
mkdir /tmp/ivy-dev-tmp
cp -R actions apps categories devices emblems gtk mimetypes places status /tmp/ivy-dev-tmp
#convert them into png
cd /tmp/ivy-dev-tmp
for svgsymlinks in `find  -wholename "*.svg"`; do
	ln -sf "`readlink $svgsymlinks|sed 's/\.svg$/\.png/'`" "`ls $svgsymlinks|sed 's/\.svg$/\.png/'`"
done
find  -wholename "*.svg" -exec rm -rf {} \;
#copy the pngs to the png theme
cp -R /tmp/ivy-dev-tmp/* $basedir/ivy/16
cp -R /tmp/ivy-dev-tmp/* $basedir/ivy/22
cp -R /tmp/ivy-dev-tmp/* $basedir/ivy/24
cp -R /tmp/ivy-dev-tmp/* $basedir/ivy/32
cp -R /tmp/ivy-dev-tmp/* $basedir/ivy/48
rm -R /tmp/ivy-dev-tmp
cd $basedir
#temporary fix for bigger icons than 48px
cp -R $basedir/ivy-dev/48 $basedir/ivy/scalable
gtk-update-icon-cache ivy
#7z a -mx=9 -m0=PPMd -mmem=512m -ms=on ivy ivy
echo "done, you can now copy the ivy folder to your icon dir($HOME/.icons) or ($HOME/.kde/share/icons) for KDE"
