#!/bin/bash
basedir="$(dirname "$(readlink -f "${0}")")"
cd $basedir
mkdir -p /tmp/ivy
cp -R "$basedir"/ivy-dev/48/actions /tmp/ivy
cp -R "$basedir"/ivy-dev/48/apps /tmp/ivy
cp -R "$basedir"/ivy-dev/48/categories /tmp/ivy
cp -R "$basedir"/ivy-dev/48/devices /tmp/ivy
cp -R "$basedir"/ivy-dev/48/emblems /tmp/ivy
cp -R "$basedir"/ivy-dev/48/gtk /tmp/ivy
cp -R "$basedir"/ivy-dev/48/mimetypes /tmp/ivy
cp -R "$basedir"/ivy-dev/48/places /tmp/ivy
cp -R "$basedir"/ivy-dev/48/status /tmp/ivy
cp -R /tmp/ivy/* "$basedir"/ivy-dev/32
cp -R /tmp/ivy/* "$basedir"/ivy-dev/22
cp -R /tmp/ivy/* "$basedir"/ivy-dev/16
rm "$basedir"/ivy-dev/index.theme.png
cp -R "$basedir"/ivy-dev "$basedir"/ivy-svg
cd $basedir
gtk-update-icon-cache-3.0 ivy-svg
echo "done, you can now copy the ivy-svg folder to your icon dir($HOME/.icons)"
