#!/bin/bash
#somechecks
command -v inkscape >/dev/null 2>&1 || { echo >&2 "I require Inkscape but it's not installed.  Aborting."; exit 1; }
command -v convert >/dev/null 2>&1 || { echo >&2 "I require ImageMagick but it's not installed.  Aborting."; exit 1; }
command -v gtk-update-icon-cache >/dev/null 2>&1 || { echo >&2 "gtk-update-icon-cache is missing, icon cache creation will fail"; }
sleep 5
basedir="$(dirname "$(readlink -f "${0}")")"

#scaled(Qtsvg fix(https://bugs.kde.org/show_bug.cgi?id=190385) or non-scaled version
echo "Would you like to upscale all icons(icon set will be ~450MB)(Needed for all Qt apps) [Y,n]"
read input
if [[ $input == "Y" || $input == "y" ]]; then
	echo "creating scaled version" && sleep 5
sizes="16 22 32 48 64 80 96 112 128 144 160 176 192 208 224 240 256"
defaultsizes="16 22 32 48"
extrasizes="64 80 96 112 128 144 160 176 192 208 224 240 256"
indextheme=ivy-dev/index.theme.scaled
else
	echo "creating fixed version" && sleep 5
sizes="16 22 32 48"
indextheme=ivy-dev/index.theme.48
fi

cd $basedir
for size in $sizes; do
	mkdir -p $basedir/ivy/$size
done

if [[ $input == "Y" || $input == "y" ]]; then
	for defaultsize in $defaultsizes; do
		cp -R ivy-dev/$defaultsize/pool $basedir/ivy/$defaultsize
	done
	for extrasize in $extrasizes; do
		cp -R ivy-dev/48/pool $basedir/ivy/$extrasize
	done
else
	for size in $sizes; do
		cp -R ivy-dev/$size/pool $basedir/ivy/$size
	done
fi

cp ivy-dev/COPYING $basedir/ivy
cp ivy-dev/COPYING.pdf $basedir/ivy
cp $indextheme $basedir/ivy/index.theme

#coverting the svgs to pngs
for size in $sizes; do
	cd $basedir/ivy/$size/pool
		for name in `find  -wholename "*.svg"`; do
		inkscape -z --export-area-page --export-width=$size --export-height=$size --export-png="`echo "$name" | sed "s/\.\w*$/.png/"`" "$name"
		done
	rm *.svg
done

#copying symlinks
cd $basedir/ivy-dev/48/
mkdir /tmp/ivy-dev-tmp
cp -R actions apps categories devices emblems gtk mimetypes places status /tmp/ivy-dev-tmp
#convert them into png
cd /tmp/ivy-dev-tmp
for svgsymlinks in `find  -wholename "*.svg"`; do
	ln -sf "`readlink $svgsymlinks|sed 's/\.svg$/\.png/'`" "`ls $svgsymlinks|sed 's/\.svg$/\.png/'`"
done
find  -wholename "*.svg" -exec rm -rf {} \;

#copy the pngs to the png theme
cd $basedir
for size in $sizes; do
	cp -R /tmp/ivy-dev-tmp/* $basedir/ivy/$size
done
rm -R /tmp/ivy-dev-tmp

#fix 24px icons
cd $basedir
cp -R $basedir/ivy/22 $basedir/ivy/24
cd $basedir/ivy/24/pool
for name24 in `find  -wholename "*.png"`; do
	convert -gravity center -extent 24x24 -background Transparent "$name24" -set colorspace RGB "$name24"
done

#create a icon cache
cd $basedir
gtk-update-icon-cache ivy
#7z a -mx=9 -m0=PPMd -mmem=512m -ms=on ivy ivy
echo "done, you can now copy the ivy folder to your icon dir($HOME/.icons) or ($HOME/.kde/share/icons) for KDE"
