[Icon Theme]
Name=Ivy(SVG)
Comment=Ex Rodentium Xfce theme
Example=text-x-script
Inherits=hicolor, Tango, Tangoish KDE, Gnome

Directories=16/actions,16/apps,16/categories,16/devices,16/emblems,16/emotes,16/mimetypes,16/places,16/status,16/gtk,22/actions,22/apps,22/categories,22/devices,22/emblems,22/emotes,22/mimetypes,22/places,22/status,22/gtk,32/actions,32/apps,32/categories,32/devices,32/emblems,32/emotes,32/mimetypes,32/places,32/status,32/gtk,48/actions,48/apps,48/categories,48/devices,48/emblems,48/emotes,48/mimetypes,48/places,48/status,48/gtk

#######
#KDE-STuff
#######
DisplayDepth=32

LinkOverlay=
LockOverlay=
ShareOverlay=
ZipOverlay=

DesktopDefault=48
DesktopSizes=16,22,32,48
ToolbarDefault=16
ToolbarSizes=16,22,32,48
MainToolbarDefault=16
MainToolbarSizes=16,22,32,48
SmallDefault=16
SmallSizes=16,22,32,48
PanelDefault=22
PanelSizes=16,22,32,48
DialogDefault=22
DialogSizes=16,24,32,48

##########################
## Freedesktop.org/KDE naming
## http://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html
## http://websvn.kde.org/trunk/kdesupport/oxygen-icons/
## NO GNOME NAMING SUPPORT! :P
##########################
######
# 16px
######

[16/actions]
Size=16
Context=Actions
Type=Threshold

[16/apps]
Size=16
Context=Applications
Type=Threshold

[16/categories]
Size=16
Context=Categories
Type=Threshold

[16/devices]
Size=16
Context=Devices
Type=Threshold

[16/emblems]
Size=16
Context=Emblems
Type=Threshold

[16/emotes]
Size=16
Context=Emotes
Type=Threshold

[16/mimetypes]
Size=16
Context=MimeTypes
Type=Threshold

[16/places]
Size=16
Context=Places
Type=Threshold

[16/status]
Size=16
Context=Status
Type=Threshold

######
# 22px
######

[22/actions]
Size=22
Context=Actions
Type=Threshold

[22/apps]
Size=22
Context=Applications
Type=Threshold

[22/categories]
Size=22
Context=Categories
Type=Threshold

[22/devices]
Size=22
Context=Devices
Type=Threshold

[22/emblems]
Size=22
Context=Emblems
Type=Threshold

[22/emotes]
Size=22
Context=Emotes
Type=Threshold

[22/mimetypes]
Size=22
Context=MimeTypes
Type=Threshold

[22/places]
Size=22
Context=Places
Type=Threshold

[22/status]
Size=22
Context=Status
Type=Threshold

######
# 32px
######

[32/actions]
Size=32
Context=Actions
Type=Threshold

[32/apps]
Size=32
Context=Applications
Type=Threshold

[32/categories]
Size=32
Context=Categories
Type=Threshold

[32/devices]
Size=32
Context=Devices
Type=Threshold

[32/emblems]
Size=32
Context=Emblems
Type=Threshold

[32/emotes]
Size=32
Context=Emotes
Type=Threshold

[32/mimetypes]
Size=32
Context=MimeTypes
Type=Threshold

[32/places]
Size=32
Context=Places
Type=Threshold

[32/status]
Size=32
Context=Status
Type=Threshold

######
# 48px
######

[48/actions]
Size=48
Context=Actions
Type=Threshold

[48/apps]
Size=48
Context=Applications
Type=Threshold

[48/categories]
Size=48
Context=Categories
Type=Threshold

[48/devices]
Size=48
Context=Devices
Type=Threshold

[48/emblems]
Size=48
Context=Emblems
Type=Threshold

[48/emotes]
Size=48
Context=Emotes
Type=Threshold

[48/mimetypes]
Size=48
Context=MimeTypes
Type=Threshold

[48/places]
Size=48
Context=Places
Type=Threshold

[48/status]
Size=48
Context=Status
Type=Threshold

##########################
## Current GTK3.8 Icons
##########################

[16/gtk]
Size=16
Context=Stock
Type=Threshold

[22/gtk]
Size=22
Context=Stock
Type=Threshold

[32/gtk]
Size=32
Context=Stock
Type=Threshold

[48/gtk]
Size=48
Context=Stock
Type=Threshold
