[Icon Theme]
Name=Ivy(test theme)
Comment=svg only => terrible loading times
Example=text-x-script
Inherits=hicolor, locolor, Tango, gnome, oxygen

Directories=48/actions,48/apps,48/categories,48/devices,48/emblems,48/emotes,48/mimetypes,48/places,48/status,48/gtk

#######
#KDE-STuff
#######
DisplayDepth=32

LinkOverlay=
LockOverlay=
ShareOverlay=
ZipOverlay=

DesktopDefault=48
DesktopSizes=16,22,32,48
ToolbarDefault=16
ToolbarSizes=16,22,32
MainToolbarDefault=16
MainToolbarSizes=16,22,32
SmallDefault=16
SmallSizes=16,22,32,48
PanelDefault=22
PanelSizes=16,22,32,48
DialogDefault=48
DialogSizes=16,24,32,48

##########################
## Freedesktop.org/KDE naming
## http://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html
## http://websvn.kde.org/trunk/kdesupport/oxygen-icons/
##########################


######
# 48px
######

[48/actions]
Size=48
Context=Actions
Type=Scalable

[48/apps]
Size=48
Context=Applications
Type=Scalable

[48/categories]
Size=48
Context=Categories
Type=Scalable

[48/devices]
Size=48
Context=Devices
Type=Scalable

[48/emblems]
Size=48
Context=Emblems
Type=Scalable

[48/emotes]
Size=48
Context=Emotes
Type=Scalable

[48/mimetypes]
Size=48
Context=MimeTypes
Type=Scalable

[48/places]
Size=48
Context=Places
Type=Scalable

[48/status]
Size=48
Context=Status
Type=Scalable

##########################
## Current GTK3.8 Icons
##########################

[48/gtk]
Size=48
Context=Stock
Type=Scalable
